# Generated by Django 3.2.6 on 2021-09-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderItems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='order_id',
            new_name='order',
        ),
    ]
