# Generated by Django 3.2.6 on 2021-08-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.IntegerField(choices=[(1, 'Card'), (2, 'Cash')], verbose_name='Payment Method')),
            ],
        ),
    ]
