# Generated by Django 3.2.6 on 2021-10-08 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='order_items_qantity',
            new_name='order_items_quantity',
        ),
    ]
