# Generated by Django 3.2.6 on 2021-09-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Paid')], default=1, verbose_name='Payment Method'),
        ),
    ]
