# Generated by Django 3.2.6 on 2021-09-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_shipping_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.IntegerField(choices=[(1, 'Planning'), (2, 'Shipping'), (3, 'Complete')], default=1, verbose_name='Shipping status'),
        ),
    ]
