version: '3.7'

services:

  db:
    image: postgres:13.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    env_file:
      - ../.env
    restart: unless-stopped

volumes:
  postgres_data:
