# Generated by Django 3.2.6 on 2021-11-11 10:28

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ProductApp.product')),
            ],
            options={
                'verbose_name_plural': 'Product advanced description',
            },
        ),
    ]
