# Generated by Django 3.2.6 on 2021-09-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0002_auto_20210917_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product categories'},
        ),
        migrations.AlterModelOptions(
            name='productmedia',
            options={'verbose_name_plural': 'Product media'},
        ),
        migrations.AlterModelOptions(
            name='productsubcategory',
            options={'verbose_name_plural': 'Product subcategories'},
        ),
        migrations.AddField(
            model_name='review',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='image',
            field=models.ImageField(default='default_image/default.png', upload_to='product_media_image'),
        ),
    ]
