# Generated by Django 3.2.6 on 2021-10-08 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProductApp', '0003_auto_20210927_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='media_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'picture'), (1, 'video_link')]),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.PositiveSmallIntegerField(choices=[(0, 'none'), (1, 'like'), (2, 'dislike')])),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ProductApp.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
