# Generated by Django 3.2 on 2021-08-30 16:30

import UserApp.managers
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('firstName', models.CharField(max_length=40, verbose_name='first name')),
                ('lastName', models.CharField(max_length=40, verbose_name='last name')),
                ('middleName', models.CharField(blank=True, max_length=40, verbose_name='middle name')),
                ('birthDate', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('registerDate', models.DateField(auto_now_add=True, verbose_name='date of registration')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='phone number')),
                ('role', models.IntegerField(choices=[(0, 'user'), (1, 'admin')], default=0, verbose_name='role')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', UserApp.managers.UserManager()),
            ],
        ),
    ]