# Generated by Django 3.2 on 2021-08-31 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_auto_20210831_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
