# Generated by Django 3.2.6 on 2021-09-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_alter_user_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, default='', max_length=40, unique=True, verbose_name='telegram id'),
            preserve_default=False,
        ),
    ]
