# Generated by Django 3.2 on 2021-09-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default_profile_pictures/default_pic.svg', upload_to='profile_pictures/', verbose_name='profile picture'),
        ),
    ]
