# Generated by Django 3.2.6 on 2021-09-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_alter_user_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(default=None, max_length=40, null=True, unique=True, verbose_name='telegram id'),
        ),
    ]
